name: 'Discord Github Notification'
description: 'GitHub Action Marketplace Action to Allow Discord to Receive GitHub Notifications'
author: 'aleph kim'
inputs:
  discord-webhook-url:
    description: 'The Discord webhook URL.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send Discord Notification
      run: |
        curl -X POST ${{ inputs.discord-webhook-url }} \
        -H "Content-Type: application/json" \
        -d "{\"content\": \"New PR opened: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}\"}"
branding:
  color: 'blue'
  icon: 'bell'