name: 'Discord PR Notifier'
description: 'Send a notification to Discord when a pull request is opened, synchronized, or reopened.'
author: 'Your Name'
inputs:
  discord-webhook-url:
    description: 'The Discord webhook URL.'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send Discord Notification
      shell: bash
      run: |
        curl -X POST ${{ inputs.discord-webhook-url }} \
        -H "Content-Type: application/json" \
        -d "{\"content\": \"New PR opened: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}\"}"
branding:
  color: 'blue'
  icon: 'bell'
