name: 'Discord Github Notification'
description: 'GitHub Action Marketplace Action to Allow Discord to Receive GitHub Notifications'
author: 'Aleph Kim'
inputs:
  discord-webhook-url:
    description: 'The Discord webhook URL.'
    required: true
  language:
    description: 'The language for notifications (korean or english).'
    required: false
    default: 'korean'
runs:
  using: 'composite'
  steps:
    - name: Checkout deployer's repository for messages.json
      uses: actions/checkout@v2
      with:
        repository: 'Aleph-Kim/discord-github-notification'
        path: messages-repo

    - name: Read Notification Messages
      id: read-messages
      shell: bash
      run: |
        MESSAGES=$(cat messages-repo/messages.json | jq -c . | sed 's/\\n/\\\\n/g')
        echo "MESSAGES=$MESSAGES" >> $GITHUB_ENV

    - name: Send Discord Notification for PR Events
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        PR_ACTION=$(jq -r .action < $GITHUB_EVENT_PATH)
        PR_TITLE=$(jq -r .pull_request.title < $GITHUB_EVENT_PATH)
        PR_USER=$(jq -r .pull_request.user.login < $GITHUB_EVENT_PATH)
        PR_URL=$(jq -r .pull_request.html_url < $GITHUB_EVENT_PATH)
        LANGUAGE=${{ inputs.language }}
        MESSAGE_KEY="PR_${PR_ACTION^^}"
        MESSAGE=$(echo $MESSAGES | jq -r ".${LANGUAGE}.${MESSAGE_KEY}")
        MESSAGE=$(echo $MESSAGE | sed "s|{title}|$PR_TITLE|" | sed "s|{user}|$PR_USER|" | sed "s|{url}|$PR_URL|")
        curl -X POST ${{ inputs.discord-webhook-url }} \
        -H "Content-Type: application/json" \
        -d "{\"content\": \"${MESSAGE}\"}"

    - name: Send Discord Notification for Merged PRs
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      shell: bash
      run: |
        PR_TITLE=$(jq -r .pull_request.title < $GITHUB_EVENT_PATH)
        PR_USER=$(jq -r .pull_request.user.login < $GITHUB_EVENT_PATH)
        PR_URL=$(jq -r .pull_request.html_url < $GITHUB_EVENT_PATH)
        LANGUAGE=${{ inputs.language }}
        MESSAGE_KEY="PR_MERGED"
        MESSAGE=$(echo $MESSAGES | jq -r ".${LANGUAGE}.${MESSAGE_KEY}")
        MESSAGE=$(echo $MESSAGE | sed "s|{title}|$PR_TITLE|" | sed "s|{user}|$PR_USER|" | sed "s|{url}|$PR_URL|")
        curl -X POST ${{ inputs.discord-webhook-url }} \
        -H "Content-Type: application/json" \
        -d "{\"content\": \"${MESSAGE}\"}"

    - name: Send Discord Notification for Branch Events
      if: github.event.ref_type == 'branch'
      shell: bash
      run: |
        EVENT_NAME=${{ github.event_name }}
        BRANCH_NAME=$(jq -r .ref < $GITHUB_EVENT_PATH)
        BRANCH_USER=$(jq -r .sender.login < $GITHUB_EVENT_PATH)
        REPO_URL=$(jq -r .repository.html_url < $GITHUB_EVENT_PATH)
        LANGUAGE=${{ inputs.language }}
        MESSAGE_KEY="BRANCH_${EVENT_NAME^^}"
        MESSAGE=$(echo $MESSAGES | jq -r ".${LANGUAGE}.${MESSAGE_KEY}")

        if [[ "$EVENT_NAME" == 'create' ]]; then
          BRANCH_URL="${REPO_URL}/tree/${BRANCH_NAME}"
        elif [[ "$EVENT_NAME" == 'delete' ]]; then
          BRANCH_URL="${REPO_URL}/branches"
        fi

        MESSAGE=$(echo $MESSAGE | sed "s|{title}|$BRANCH_NAME|" | sed "s|{user}|$BRANCH_USER|" | sed "s|{url}|$BRANCH_URL|")
        curl -X POST ${{ inputs.discord-webhook-url }} \
        -H "Content-Type: application/json" \
        -d "{\"content\": \"${MESSAGE}\"}"
        
    - name: Send Discord Notification for Issue Events
      if: github.event_name == 'issues'
      shell: bash
      run: |
        ISSUE_ACTION=$(jq -r .action < $GITHUB_EVENT_PATH)
        ISSUE_TITLE=$(jq -r .issue.title < $GITHUB_EVENT_PATH)
        ISSUE_USER=$(jq -r .issue.user.login < $GITHUB_EVENT_PATH)
        ISSUE_URL=$(jq -r .issue.html_url < $GITHUB_EVENT_PATH)
        LANGUAGE=${{ inputs.language }}
        MESSAGE_KEY="ISSUE_${ISSUE_ACTION^^}"
        MESSAGE=$(echo $MESSAGES | jq -r ".${LANGUAGE}.${MESSAGE_KEY}")
        MESSAGE=$(echo $MESSAGE | sed "s|{title}|$ISSUE_TITLE|" | sed "s|{user}|$ISSUE_USER|" | sed "s|{url}|$ISSUE_URL|")
        curl -X POST ${{ inputs.discord-webhook-url }} \
        -H "Content-Type: application/json" \
        -d "{\"content\": \"${MESSAGE}\"}"
branding:
  color: 'blue'
  icon: 'bell'
